"""Generate packages/typescript/src/native-signatures.ts: typed arguments and results of the native Mini App methods.

    python scripts/build_native_signatures.py           # write the module
    python scripts/build_native_signatures.py --check   # fail when it is stale

Parameter names and optionality come from the official signatures in catalog/mini-app-index.json
(`start(params[, callback])`); types come from the documentation table catalog/mini-app-types.json. The generator
refuses a table whose methods or parameters differ from the official signatures, so a documentation update cannot
leave a stale or invented parameter behind.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / 'catalog/mini-app-index.json'
TYPES = ROOT / 'catalog/mini-app-types.json'
OUTPUT = ROOT / 'packages/typescript/src/native-signatures.ts'


def official_parameters(signature: str) -> list[tuple[str, bool]]:
    """(name, optional) pairs of an official signature such as `setEmojiStatus(custom_emoji_id[, params, callback])`."""
    inner = signature[signature.index('(') + 1 : signature.rindex(')')]
    result: list[tuple[str, bool]] = []
    depth, name, optional = 0, '', False
    for char in inner + ',':
        if char == '[':
            depth += 1
        elif char == ']':
            depth -= 1
        elif char == ',':
            if name:
                result.append((name, optional))
            name = ''
        elif not char.isspace():
            if not name:
                optional = depth > 0  # a parameter is optional when it starts inside brackets
            name += char
    if depth:
        raise ValueError(f'Unbalanced brackets in {signature}')
    return result


def render(index: dict, table: dict) -> str:
    official = {item['path']: official_parameters(item['signature']) for item in index['methods']}
    methods = table['methods']
    if set(methods) != set(official):
        missing, extra = sorted(set(official) - set(methods)), sorted(set(methods) - set(official))
        raise ValueError(f'Type table differs from the official methods: missing {missing}, extra {extra}')
    lines = [
        '// Generated by scripts/build_native_signatures.py. Do not edit: change catalog/mini-app-types.json.',
        '// Parameter names and optionality follow the official signatures (catalog/mini-app-index.json);',
        f"// types follow {table['source']} (checked {table['checked_date']}).",
        "import type {TelegramNativeEvent, TelegramNativeMethod} from './native-catalog.js';",
        '',
    ]
    for name, value in table['declarations'].items():
        keyword = 'interface' if value.startswith('{') and '<' not in name else 'type'
        lines.append(f'export interface {name} {value}' if keyword == 'interface' else f'export type {name} = {value};')
    lines += ['', '/** Documented arguments and result of every native method, keyed by its path. */',
              'export interface TelegramNativeSignatures {']
    for path in sorted(methods):
        declared = list(methods[path]['parameters'].items())
        expected = official[path]
        if [name for name, _ in declared] != [name for name, _ in expected]:
            raise ValueError(f'{path}: parameters {[n for n, _ in declared]} differ from the official {expected}')
        arguments = ', '.join(f"{name}{'?' if optional else ''}: {kind}"
                              for (name, kind), (_, optional) in zip(declared, expected))
        lines.append(f"  '{path}': ({arguments}) => {methods[path]['returns']};")
    lines += [
        '}',
        '',
        'type Exact<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;',
        'type Assert<T extends true> = T;',
        '/** Compile-time proof that every catalog method has exactly one signature. */',
        'export type TelegramNativeSignaturesComplete = Assert<Exact<keyof TelegramNativeSignatures, TelegramNativeMethod>>;',
        'export type TelegramNativeArguments<P extends TelegramNativeMethod> = Parameters<TelegramNativeSignatures[P]>;',
        'export type TelegramNativeResult<P extends TelegramNativeMethod> = ReturnType<TelegramNativeSignatures[P]>;',
        '',
    ]
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true', help='fail instead of writing when the module is stale')
    args = parser.parse_args()
    content = render(json.loads(INDEX.read_text(encoding='utf-8')), json.loads(TYPES.read_text(encoding='utf-8')))
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding='utf-8') != content:
            sys.stderr.write(f'{OUTPUT.relative_to(ROOT)} is stale; run python scripts/build_native_signatures.py\n')
            return 1
    else:
        OUTPUT.write_text(content, encoding='utf-8')
    print(json.dumps({'passed': True, 'methods': len(json.loads(TYPES.read_text(encoding='utf-8'))['methods']),
                      'check': args.check}))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
