// Generated by scripts/build_native_signatures.py. Do not edit: change catalog/mini-app-types.json.
// Parameter names and optionality follow the official signatures (catalog/mini-app-index.json);
// types follow https://core.telegram.org/bots/webapps (checked 2026-10-07).
import type {TelegramNativeEvent, TelegramNativeMethod} from './native-catalog.js';

export type TelegramNativeObject = Readonly<Record<string, unknown>>;
export type TelegramColor = `#${string}` | 'bg_color' | 'secondary_bg_color';
export type TelegramBottomBarColor = TelegramColor | 'bottom_bar_bg_color';
export type TelegramEventHandler = (...args: never[]) => void;
export interface PopupButton { id?: string; type?: 'default' | 'ok' | 'close' | 'cancel' | 'destructive'; text?: string }
export interface PopupParams { title?: string; message: string; buttons?: PopupButton[] }
export interface ScanQrPopupParams { text?: string }
export interface StoryWidgetLink { url: string; name?: string }
export interface StoryShareParams { text?: string; widget_link?: StoryWidgetLink }
export interface EmojiStatusParams { duration?: number }
export interface DownloadFileParams { url: string; file_name: string }
export interface OpenLinkOptions { try_instant_view?: boolean }
export interface BottomButtonParams { text?: string; color?: string; text_color?: string; has_shine_effect?: boolean; position?: 'left' | 'right' | 'top' | 'bottom'; is_active?: boolean; is_visible?: boolean; icon_custom_emoji_id?: string }
export interface BiometricRequestAccessParams { reason?: string }
export interface BiometricAuthenticateParams { reason?: string }
export interface MotionStartParams { refresh_rate?: number }
export interface DeviceOrientationStartParams { refresh_rate?: number; need_absolute?: boolean }
export interface LocationData { latitude: number; longitude: number; altitude: number | null; course: number | null; speed: number | null; horizontal_accuracy: number | null; vertical_accuracy: number | null; course_accuracy: number | null; speed_accuracy: number | null }
export type StorageCallback<T> = (error: string | null, result?: T) => void;
export type InlineQueryChatType = 'users' | 'bots' | 'groups' | 'channels';
export type InvoiceStatus = 'paid' | 'cancelled' | 'failed' | 'pending';
export type HomeScreenStatus = 'unsupported' | 'unknown' | 'added' | 'missed';

/** Documented arguments and result of every native method, keyed by its path. */
export interface TelegramNativeSignatures {
  'Accelerometer.start': (params: MotionStartParams, callback?: (started: boolean) => void) => TelegramNativeObject;
  'Accelerometer.stop': (callback?: (stopped: boolean) => void) => TelegramNativeObject;
  'BackButton.hide': () => TelegramNativeObject;
  'BackButton.offClick': (callback: () => void) => TelegramNativeObject;
  'BackButton.onClick': (callback: () => void) => TelegramNativeObject;
  'BackButton.show': () => TelegramNativeObject;
  'BiometricManager.authenticate': (params: BiometricAuthenticateParams, callback?: (authenticated: boolean, biometricToken?: string) => void) => TelegramNativeObject;
  'BiometricManager.init': (callback?: () => void) => TelegramNativeObject;
  'BiometricManager.openSettings': () => TelegramNativeObject;
  'BiometricManager.requestAccess': (params: BiometricRequestAccessParams, callback?: (granted: boolean) => void) => TelegramNativeObject;
  'BiometricManager.updateBiometricToken': (token: string, callback?: (updated: boolean) => void) => TelegramNativeObject;
  'CloudStorage.getItem': (key: string, callback: StorageCallback<string>) => TelegramNativeObject;
  'CloudStorage.getItems': (keys: string[], callback: StorageCallback<Record<string, string>>) => TelegramNativeObject;
  'CloudStorage.getKeys': (callback: StorageCallback<string[]>) => TelegramNativeObject;
  'CloudStorage.removeItem': (key: string, callback?: StorageCallback<boolean>) => TelegramNativeObject;
  'CloudStorage.removeItems': (keys: string[], callback?: StorageCallback<boolean>) => TelegramNativeObject;
  'CloudStorage.setItem': (key: string, value: string, callback?: StorageCallback<boolean>) => TelegramNativeObject;
  'DeviceOrientation.start': (params: DeviceOrientationStartParams, callback?: (started: boolean) => void) => TelegramNativeObject;
  'DeviceOrientation.stop': (callback?: (stopped: boolean) => void) => TelegramNativeObject;
  'DeviceStorage.clear': (callback?: StorageCallback<boolean>) => TelegramNativeObject;
  'DeviceStorage.getItem': (key: string, callback: StorageCallback<string | null>) => TelegramNativeObject;
  'DeviceStorage.removeItem': (key: string, callback?: StorageCallback<boolean>) => TelegramNativeObject;
  'DeviceStorage.setItem': (key: string, value: string, callback?: StorageCallback<boolean>) => TelegramNativeObject;
  'Gyroscope.start': (params: MotionStartParams, callback?: (started: boolean) => void) => TelegramNativeObject;
  'Gyroscope.stop': (callback?: (stopped: boolean) => void) => TelegramNativeObject;
  'HapticFeedback.impactOccurred': (style: 'light' | 'medium' | 'heavy' | 'rigid' | 'soft') => TelegramNativeObject;
  'HapticFeedback.notificationOccurred': (type: 'error' | 'success' | 'warning') => TelegramNativeObject;
  'HapticFeedback.selectionChanged': () => TelegramNativeObject;
  'LocationManager.getLocation': (callback: (location: LocationData | null) => void) => TelegramNativeObject;
  'LocationManager.init': (callback?: () => void) => TelegramNativeObject;
  'LocationManager.openSettings': () => TelegramNativeObject;
  'MainButton.disable': () => TelegramNativeObject;
  'MainButton.enable': () => TelegramNativeObject;
  'MainButton.hide': () => TelegramNativeObject;
  'MainButton.hideProgress': () => TelegramNativeObject;
  'MainButton.offClick': (callback: () => void) => TelegramNativeObject;
  'MainButton.onClick': (callback: () => void) => TelegramNativeObject;
  'MainButton.setParams': (params: BottomButtonParams) => TelegramNativeObject;
  'MainButton.setText': (text: string) => TelegramNativeObject;
  'MainButton.show': () => TelegramNativeObject;
  'MainButton.showProgress': (leaveActive: boolean) => TelegramNativeObject;
  'SecondaryButton.disable': () => TelegramNativeObject;
  'SecondaryButton.enable': () => TelegramNativeObject;
  'SecondaryButton.hide': () => TelegramNativeObject;
  'SecondaryButton.hideProgress': () => TelegramNativeObject;
  'SecondaryButton.offClick': (callback: () => void) => TelegramNativeObject;
  'SecondaryButton.onClick': (callback: () => void) => TelegramNativeObject;
  'SecondaryButton.setParams': (params: BottomButtonParams) => TelegramNativeObject;
  'SecondaryButton.setText': (text: string) => TelegramNativeObject;
  'SecondaryButton.show': () => TelegramNativeObject;
  'SecondaryButton.showProgress': (leaveActive: boolean) => TelegramNativeObject;
  'SecureStorage.clear': (callback?: StorageCallback<boolean>) => TelegramNativeObject;
  'SecureStorage.getItem': (key: string, callback: (error: string | null, value?: string | null, canRestore?: boolean) => void) => TelegramNativeObject;
  'SecureStorage.removeItem': (key: string, callback?: StorageCallback<boolean>) => TelegramNativeObject;
  'SecureStorage.restoreItem': (key: string, callback?: StorageCallback<string | null>) => TelegramNativeObject;
  'SecureStorage.setItem': (key: string, value: string, callback?: StorageCallback<boolean>) => TelegramNativeObject;
  'SettingsButton.hide': () => TelegramNativeObject;
  'SettingsButton.offClick': (callback: () => void) => TelegramNativeObject;
  'SettingsButton.onClick': (callback: () => void) => TelegramNativeObject;
  'SettingsButton.show': () => TelegramNativeObject;
  'addToHomeScreen': () => void;
  'checkHomeScreenStatus': (callback?: (status: HomeScreenStatus) => void) => void;
  'close': () => void;
  'closeScanQrPopup': () => void;
  'disableClosingConfirmation': () => void;
  'disableVerticalSwipes': () => void;
  'downloadFile': (params: DownloadFileParams, callback?: (accepted: boolean) => void) => void;
  'enableClosingConfirmation': () => void;
  'enableVerticalSwipes': () => void;
  'exitFullscreen': () => void;
  'expand': () => void;
  'hideKeyboard': () => void;
  'isVersionAtLeast': (version: string) => boolean;
  'lockOrientation': () => void;
  'offEvent': (eventType: TelegramNativeEvent, eventHandler: TelegramEventHandler) => void;
  'onEvent': (eventType: TelegramNativeEvent, eventHandler: TelegramEventHandler) => void;
  'openInvoice': (url: string, callback?: (status: InvoiceStatus) => void) => void;
  'openLink': (url: string, options?: OpenLinkOptions) => void;
  'openTelegramLink': (url: string) => void;
  'readTextFromClipboard': (callback?: (text: string | null) => void) => void;
  'ready': () => void;
  'requestChat': (req_id: string, callback?: (sent: boolean) => void) => void;
  'requestContact': (callback?: (shared: boolean, response?: unknown) => void) => void;
  'requestEmojiStatusAccess': (callback?: (granted: boolean) => void) => void;
  'requestFullscreen': () => void;
  'requestWriteAccess': (callback?: (granted: boolean) => void) => void;
  'sendData': (data: string) => void;
  'setBackgroundColor': (color: TelegramColor) => void;
  'setBottomBarColor': (color: TelegramBottomBarColor) => void;
  'setEmojiStatus': (custom_emoji_id: string, params?: EmojiStatusParams, callback?: (set: boolean) => void) => void;
  'setHeaderColor': (color: TelegramColor) => void;
  'shareMessage': (msg_id: string, callback?: (sent: boolean) => void) => void;
  'shareToStory': (media_url: string, params?: StoryShareParams) => void;
  'showAlert': (message: string, callback?: () => void) => void;
  'showConfirm': (message: string, callback?: (confirmed: boolean) => void) => void;
  'showPopup': (params: PopupParams, callback?: (buttonId: string) => void) => void;
  'showScanQrPopup': (params: ScanQrPopupParams, callback?: (text: string) => boolean | void) => void;
  'switchInlineQuery': (query: string, choose_chat_types?: InlineQueryChatType[]) => void;
  'unlockOrientation': () => void;
}

type Exact<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
type Assert<T extends true> = T;
/** Compile-time proof that every catalog method has exactly one signature. */
export type TelegramNativeSignaturesComplete = Assert<Exact<keyof TelegramNativeSignatures, TelegramNativeMethod>>;
export type TelegramNativeArguments<P extends TelegramNativeMethod> = Parameters<TelegramNativeSignatures[P]>;
export type TelegramNativeResult<P extends TelegramNativeMethod> = ReturnType<TelegramNativeSignatures[P]>;
