// Generated by scripts/build_telegram_catalog.py from official metadata.
const definitions = {
  "Accelerometer.start": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#accelerometer"
  },
  "Accelerometer.stop": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#accelerometer"
  },
  "BackButton.hide": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#backbutton"
  },
  "BackButton.offClick": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#backbutton"
  },
  "BackButton.onClick": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#backbutton"
  },
  "BackButton.show": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#backbutton"
  },
  "BiometricManager.authenticate": {
    "minVersion": "7.2",
    "url": "https://core.telegram.org/bots/webapps#biometricmanager"
  },
  "BiometricManager.init": {
    "minVersion": "7.2",
    "url": "https://core.telegram.org/bots/webapps#biometricmanager"
  },
  "BiometricManager.openSettings": {
    "minVersion": "7.2",
    "url": "https://core.telegram.org/bots/webapps#biometricmanager"
  },
  "BiometricManager.requestAccess": {
    "minVersion": "7.2",
    "url": "https://core.telegram.org/bots/webapps#biometricmanager"
  },
  "BiometricManager.updateBiometricToken": {
    "minVersion": "7.2",
    "url": "https://core.telegram.org/bots/webapps#biometricmanager"
  },
  "CloudStorage.getItem": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#cloudstorage"
  },
  "CloudStorage.getItems": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#cloudstorage"
  },
  "CloudStorage.getKeys": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#cloudstorage"
  },
  "CloudStorage.removeItem": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#cloudstorage"
  },
  "CloudStorage.removeItems": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#cloudstorage"
  },
  "CloudStorage.setItem": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#cloudstorage"
  },
  "DeviceOrientation.start": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#deviceorientation"
  },
  "DeviceOrientation.stop": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#deviceorientation"
  },
  "DeviceStorage.clear": {
    "minVersion": "9.0",
    "url": "https://core.telegram.org/bots/webapps#devicestorage"
  },
  "DeviceStorage.getItem": {
    "minVersion": "9.0",
    "url": "https://core.telegram.org/bots/webapps#devicestorage"
  },
  "DeviceStorage.removeItem": {
    "minVersion": "9.0",
    "url": "https://core.telegram.org/bots/webapps#devicestorage"
  },
  "DeviceStorage.setItem": {
    "minVersion": "9.0",
    "url": "https://core.telegram.org/bots/webapps#devicestorage"
  },
  "Gyroscope.start": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#gyroscope"
  },
  "Gyroscope.stop": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#gyroscope"
  },
  "HapticFeedback.impactOccurred": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#hapticfeedback"
  },
  "HapticFeedback.notificationOccurred": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#hapticfeedback"
  },
  "HapticFeedback.selectionChanged": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#hapticfeedback"
  },
  "LocationManager.getLocation": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#locationmanager"
  },
  "LocationManager.init": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#locationmanager"
  },
  "LocationManager.openSettings": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#locationmanager"
  },
  "MainButton.disable": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "MainButton.enable": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "MainButton.hide": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "MainButton.hideProgress": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "MainButton.offClick": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "MainButton.onClick": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "MainButton.setParams": {
    "minVersion": "9.5",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "MainButton.setText": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "MainButton.show": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "MainButton.showProgress": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.disable": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.enable": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.hide": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.hideProgress": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.offClick": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.onClick": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.setParams": {
    "minVersion": "9.5",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.setText": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.show": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecondaryButton.showProgress": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#bottombutton"
  },
  "SecureStorage.clear": {
    "minVersion": "9.0",
    "url": "https://core.telegram.org/bots/webapps#securestorage"
  },
  "SecureStorage.getItem": {
    "minVersion": "9.0",
    "url": "https://core.telegram.org/bots/webapps#securestorage"
  },
  "SecureStorage.removeItem": {
    "minVersion": "9.0",
    "url": "https://core.telegram.org/bots/webapps#securestorage"
  },
  "SecureStorage.restoreItem": {
    "minVersion": "9.0",
    "url": "https://core.telegram.org/bots/webapps#securestorage"
  },
  "SecureStorage.setItem": {
    "minVersion": "9.0",
    "url": "https://core.telegram.org/bots/webapps#securestorage"
  },
  "SettingsButton.hide": {
    "minVersion": "7.0",
    "url": "https://core.telegram.org/bots/webapps#settingsbutton"
  },
  "SettingsButton.offClick": {
    "minVersion": "7.0",
    "url": "https://core.telegram.org/bots/webapps#settingsbutton"
  },
  "SettingsButton.onClick": {
    "minVersion": "7.0",
    "url": "https://core.telegram.org/bots/webapps#settingsbutton"
  },
  "SettingsButton.show": {
    "minVersion": "7.0",
    "url": "https://core.telegram.org/bots/webapps#settingsbutton"
  },
  "addToHomeScreen": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "checkHomeScreenStatus": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "close": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "closeScanQrPopup": {
    "minVersion": "6.4",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "disableClosingConfirmation": {
    "minVersion": "6.2",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "disableVerticalSwipes": {
    "minVersion": "7.7",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "downloadFile": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "enableClosingConfirmation": {
    "minVersion": "6.2",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "enableVerticalSwipes": {
    "minVersion": "7.7",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "exitFullscreen": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "expand": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "hideKeyboard": {
    "minVersion": "9.1",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "isVersionAtLeast": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "lockOrientation": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "offEvent": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "onEvent": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "openInvoice": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "openLink": {
    "minVersion": "6.4",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "openTelegramLink": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "readTextFromClipboard": {
    "minVersion": "6.4",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "ready": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "requestChat": {
    "minVersion": "9.6",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "requestContact": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "requestEmojiStatusAccess": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "requestFullscreen": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "requestWriteAccess": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "sendData": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "setBackgroundColor": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "setBottomBarColor": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "setEmojiStatus": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "setHeaderColor": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "shareMessage": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "shareToStory": {
    "minVersion": "7.8",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "showAlert": {
    "minVersion": "6.2",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "showConfirm": {
    "minVersion": "6.2",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "showPopup": {
    "minVersion": "6.2",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "showScanQrPopup": {
    "minVersion": "6.4",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "switchInlineQuery": {
    "minVersion": "6.7",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  },
  "unlockOrientation": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#initializing-mini-apps"
  }
} as const;
export const TELEGRAM_NATIVE_METHODS = Object.freeze(Object.fromEntries(Object.entries(definitions).map(([key,value]) => [key,Object.freeze(value)]))) as Readonly<typeof definitions>;
export type TelegramNativeMethod = keyof typeof definitions;
export const TELEGRAM_NATIVE_EVENTS = Object.freeze(["accelerometerChanged", "accelerometerFailed", "accelerometerStarted", "accelerometerStopped", "activated", "backButtonClicked", "biometricAuthRequested", "biometricManagerUpdated", "biometricTokenUpdated", "clipboardTextReceived", "contactRequested", "contentSafeAreaChanged", "deactivated", "deviceOrientationChanged", "deviceOrientationFailed", "deviceOrientationStarted", "deviceOrientationStopped", "emojiStatusAccessRequested", "emojiStatusFailed", "emojiStatusSet", "fileDownloadRequested", "fullscreenChanged", "fullscreenFailed", "gyroscopeChanged", "gyroscopeFailed", "gyroscopeStarted", "gyroscopeStopped", "homeScreenAdded", "homeScreenChecked", "invoiceClosed", "locationManagerUpdated", "locationRequested", "mainButtonClicked", "popupClosed", "qrTextReceived", "safeAreaChanged", "scanQrPopupClosed", "secondaryButtonClicked", "settingsButtonClicked", "shareMessageFailed", "shareMessageSent", "themeChanged", "viewportChanged", "writeAccessRequested"] as const);
export type TelegramNativeEvent = typeof TELEGRAM_NATIVE_EVENTS[number];
const eventDefinitions = {
  "accelerometerChanged": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "accelerometerFailed": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "accelerometerStarted": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "accelerometerStopped": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "activated": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "backButtonClicked": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "biometricAuthRequested": {
    "minVersion": "7.2",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "biometricManagerUpdated": {
    "minVersion": "7.2",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "biometricTokenUpdated": {
    "minVersion": "7.2",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "clipboardTextReceived": {
    "minVersion": "6.4",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "contactRequested": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "contentSafeAreaChanged": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "deactivated": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "deviceOrientationChanged": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "deviceOrientationFailed": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "deviceOrientationStarted": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "deviceOrientationStopped": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "emojiStatusAccessRequested": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "emojiStatusFailed": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "emojiStatusSet": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "fileDownloadRequested": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "fullscreenChanged": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "fullscreenFailed": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "gyroscopeChanged": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "gyroscopeFailed": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "gyroscopeStarted": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "gyroscopeStopped": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "homeScreenAdded": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "homeScreenChecked": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "invoiceClosed": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "locationManagerUpdated": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "locationRequested": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "mainButtonClicked": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "popupClosed": {
    "minVersion": "6.2",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "qrTextReceived": {
    "minVersion": "6.4",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "safeAreaChanged": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "scanQrPopupClosed": {
    "minVersion": "7.7",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "secondaryButtonClicked": {
    "minVersion": "7.10",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "settingsButtonClicked": {
    "minVersion": "6.1",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "shareMessageFailed": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "shareMessageSent": {
    "minVersion": "8.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "themeChanged": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "viewportChanged": {
    "minVersion": "6.0",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  },
  "writeAccessRequested": {
    "minVersion": "6.9",
    "url": "https://core.telegram.org/bots/webapps#events-available-for-mini-apps"
  }
} as const;
export const TELEGRAM_NATIVE_EVENT_DETAILS = Object.freeze(Object.fromEntries(Object.entries(eventDefinitions).map(([key,value]) => [key,Object.freeze(value)]))) as Readonly<typeof eventDefinitions>;
